# Generated by Django 5.2.1 on 2025-06-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0002_class_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='faculty',
            field=models.CharField(choices=[('Sceince', 'Science'), ('Computer_Scence', 'Computer_science')], default='N/A', max_length=30, verbose_name='Faculty'),
        ),
    ]
