# Generated by Django 5.2.1 on 2025-06-17 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0003_alter_class_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='faculty',
            field=models.CharField(choices=[('Sceince', 'Science'), ('Computer_Scence', 'Computer_science'), ('None', 'None')], default='N/A', max_length=30, verbose_name='Faculty'),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled', max_length=100)),
                ('book_image', models.ImageField(blank=True, upload_to='book_image')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='data_class.class')),
                ('book_Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Subject', to='data_class.subject')),
            ],
            options={
                'verbose_name': 'book',
            },
        ),
    ]
