# Generated by Django 5.2.1 on 2025-06-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0004_alter_class_faculty_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
