# Generated by Django 5.2.1 on 2025-06-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0005_delete_books'),
        ('teacher', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='notes_pdfs')),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
