# Generated by Django 5.2.1 on 2025-06-17 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0006_assignments'),
        ('teacher', '0008_alter_teacher_teacher_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teacher.teacher'),
        ),
    ]
