# Generated by Django 5.2.1 on 2025-06-17 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0007_alter_assignments_teacher'),
        ('student', '0005_alter_parent_info_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='project title')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='', verbose_name='Project content')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', verbose_name='Project Status')),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='student.student_info')),
            ],
            options={
                'verbose_name': 'project',
            },
        ),
    ]
