# Generated by Django 5.2.1 on 2025-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0008_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_image',
            field=models.ImageField(blank=True, upload_to='class_image/'),
        ),
    ]
