# Generated by Django 5.2.1 on 2025-06-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0009_class_class_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_image',
            field=models.ImageField(blank=True, upload_to='class_image/', verbose_name='class_image'),
        ),
    ]
