# Generated by Django 5.2.1 on 2025-06-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0011_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
