# Generated by Django 5.2.1 on 2025-06-21 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0012_delete_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignments',
            options={'verbose_name': 'Assigment', 'verbose_name_plural': 'Assigments'},
        ),
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_class.subject'),
        ),
    ]
