# Generated by Django 5.2.1 on 2025-06-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0013_alter_assignments_options_project_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='N/A', verbose_name='description'),
        ),
    ]
