# Generated by Django 5.2.4 on 2025-08-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0014_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.PositiveIntegerField(verbose_name='Grade/Class'),
        ),
    ]
