# Generated by Django 5.2.4 on 2025-08-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0015_alter_class_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(verbose_name='Grade/Class'),
        ),
    ]
