# Generated by Django 5.2.4 on 2025-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0016_alter_class_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='faculty',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Section'),
        ),
    ]
