# Generated by Django 5.2.5 on 2025-08-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0017_alter_class_faculty_alter_class_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teacher_message',
            field=models.TextField(blank=True, null=True, verbose_name='message form techer'),
        ),
    ]
