# Generated by Django 5.2.5 on 2025-08-13 12:49

import data_class.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0018_project_teacher_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teacher_message',
            field=models.TextField(blank=True, null=True, verbose_name='message form teacher'),
        ),
        migrations.CreateModel(
            name='YEAR_MONTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.IntegerField(verbose_name='number_of_holiday')),
                ('unexpected_holiday', models.IntegerField(verbose_name='unexpected_holidays')),
                ('number_of_days', models.IntegerField(verbose_name='number_of_days_in_month')),
                ('month', models.CharField(choices=[('Baishak', 'Baishak'), ('Jestha', 'Jestha'), ('Ashar', 'Ashar'), ('Shrawan', 'Shrawan'), ('Bhadra', 'Bhadra'), ('Ashwin', 'Ashwin'), ('Kartik', 'Kartik'), ('Mangsir', 'Mangsir'), ('Poush', 'Poush'), ('Magh', 'Magh'), ('Falgun', 'Falgun'), ('Chaitra', 'Chaitra')], max_length=10, verbose_name='MONTH')),
                ('current_year', models.IntegerField(default=data_class.models.get_current_year)),
            ],
            options={
                'unique_together': {('current_year', 'month')},
            },
        ),
    ]
