# Generated by Django 5.2.5 on 2025-08-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0019_alter_project_teacher_message_year_month'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='year_month',
            unique_together=set(),
        ),
    ]
