# Generated by Django 5.2.5 on 2025-08-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0020_alter_year_month_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
    ]
