# Generated by Django 5.2.5 on 2025-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0021_alter_class_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_month',
            name='month',
            field=models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=10, verbose_name='MONTH'),
        ),
    ]
