# Generated by Django 5.2.5 on 2025-08-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0022_alter_year_month_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_month',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='MONTH'),
        ),
    ]
