# Generated by Django 5.2.1 on 2025-06-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0005_delete_books'),
        ('teacher', '0004_alter_teacher_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='head_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_teacher', to='data_class.class'),
        ),
    ]
