# Generated by Django 5.2.1 on 2025-06-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_head_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
