# Generated by Django 5.2.1 on 2025-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0006_assignments'),
        ('teacher', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_class',
            field=models.ManyToManyField(related_name='class_teacher', to='data_class.class', verbose_name='teacher_assigned_class'),
        ),
    ]
