# Generated by Django 5.2.4 on 2025-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='refrence_code',
            field=models.CharField(default='n?A', verbose_name='refrence_code'),
        ),
    ]
