# Generated by Django 5.2.4 on 2025-07-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_alter_galleryimage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
    ]
