# Generated by Django 5.2.4 on 2025-07-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_remove_news_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head_faculty',
            name='teacher_social_link',
        ),
    ]
