# Generated by Django 5.2.4 on 2025-07-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_remove_head_faculty_teacher_social_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='head_faculty',
            name='teacher_faculty',
            field=models.CharField(choices=[('Science', 'Science'), ('Computer Science', 'Computer Science'), ('Education', 'Education'), ('Hotel Management', 'Hotel Management'), ('Management', 'Manage')], default='None'),
        ),
    ]
