# Generated by Django 5.2.4 on 2025-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_remove_galleryimage_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_faculty',
            name='teacher_subject',
            field=models.CharField(default='not given', verbose_name='teacher_subject_names'),
        ),
    ]
