# Generated by Django 5.2.4 on 2025-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0031_head_faculty_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head_faculty',
            name='teacher_faculty',
            field=models.CharField(choices=[('Science', 'Science'), ('Computer Science', 'Computer Science'), ('Education', 'Education'), ('Hotel Management', 'Hotel Management'), ('Management', 'Management')], default='None'),
        ),
    ]
