# Generated by Django 5.2.4 on 2025-07-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0032_alter_head_faculty_teacher_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quick_acess_academics',
        ),
        migrations.DeleteModel(
            name='Quick_acess_admission',
        ),
    ]
