# Generated by Django 5.2.4 on 2025-07-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_delete_quick_acess_academics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.ImageField(upload_to='member/')),
                ('member_name', models.CharField(verbose_name='Name')),
                ('member_contact', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
