# Generated by Django 5.2.4 on 2025-07-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0034_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='is_active',
        ),
    ]
