# Generated by Django 5.2.4 on 2025-07-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0035_remove_slider_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
