# Generated by Django 5.2.4 on 2025-07-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0036_news_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, upload_to='supporting/files'),
        ),
    ]
