# Generated by Django 5.2.5 on 2025-08-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0037_news_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'schol name', 'verbose_name_plural': 'School name'},
        ),
    ]
