# Generated by Django 5.2.1 on 2025-06-14 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_class', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.IntegerField(max_length=10, verbose_name='student_code')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(verbose_name='student_age')),
                ('email', models.EmailField(max_length=254, verbose_name='student_email')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.class', verbose_name='student_class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Associated_Student')),
            ],
            options={
                'verbose_name': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='parent_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=30, verbose_name='parent_name')),
                ('contact', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, verbose_name='parent`s Email')),
                ('associated_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student_info', verbose_name='student_name')),
            ],
            options={
                'verbose_name': 'Parent_info',
            },
        ),
    ]
