# Generated by Django 5.2.1 on 2025-06-17 06:11

import student.code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='student_code',
            field=models.CharField(default=student.code.generate_unique_code, editable=False, max_length=10, unique=True, verbose_name='Student Code'),
        ),
    ]
