# Generated by Django 5.2.1 on 2025-06-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_info_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='student_profile',
            field=models.ImageField(blank=True, upload_to='student/'),
        ),
    ]
