# Generated by Django 5.2.1 on 2025-06-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_info_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_info',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
