# Generated by Django 5.2.1 on 2025-06-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_parent_info_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='Roll_num',
            field=models.IntegerField(default=0, verbose_name='student_roll number'),
        ),
    ]
