# Generated by Django 5.2.1 on 2025-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_info_roll_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent_info',
            name='associated_student',
        ),
        migrations.AddField(
            model_name='parent_info',
            name='associated_student',
            field=models.ManyToManyField(to='student.student_info', verbose_name='student_name'),
        ),
    ]
