# Generated by Django 5.2.1 on 2025-06-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_parent_info_associated_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent_info',
            name='associated_student',
        ),
        migrations.AddField(
            model_name='student_info',
            name='parent',
            field=models.ManyToManyField(to='student.parent_info', verbose_name='student_parent'),
        ),
    ]
