# Generated by Django 5.2.1 on 2025-06-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_student_info_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent_info',
            name='associated_student',
        ),
    ]
