# Generated by Django 5.2.1 on 2025-06-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_parent_info_associated_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='parent',
            field=models.ManyToManyField(to='student.parent_info', verbose_name='Student`s parent'),
        ),
    ]
