# Generated by Django 5.2.4 on 2025-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_info_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='student_age'),
        ),
    ]
