# Generated by Django 5.2.4 on 2025-08-04 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0014_project_description'),
        ('student', '0017_alter_student_info_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_class.class', verbose_name='student_class'),
        ),
    ]
