# Generated by Django 5.2.4 on 2025-08-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_student_info_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='joined',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
