# Generated by Django 5.2.4 on 2025-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_student_info_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='student.parent_info', verbose_name='Student`s parent'),
        ),
    ]
