# Generated by Django 5.2.4 on 2025-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_student_info_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='adddress',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='contact',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='emergency_contact',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='emergency conmtact'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='father_name',
            field=models.CharField(blank=True, null=True, verbose_name='father_name'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='mother_name',
            field=models.CharField(blank=True, null=True, verbose_name='mother_name'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='parent_email'),
        ),
    ]
