# Generated by Django 5.2.4 on 2025-08-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_student_info_adddress_student_info_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='contact',
            new_name='parent_contact',
        ),
    ]
