# Generated by Django 5.2.4 on 2025-08-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_rename_contact_student_info_parent_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='adddress',
            new_name='address',
        ),
    ]
