# Generated by Django 5.2.4 on 2025-08-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_rename_adddress_student_info_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='Roll_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='student_roll number'),
        ),
    ]
