# Generated by Django 5.2.4 on 2025-08-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_alter_student_info_roll_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='emergency_contact',
            field=models.IntegerField(blank=True, null=True, verbose_name='emergency conmtact'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='parent_contact',
            field=models.IntegerField(blank=True, null=True, verbose_name='contact'),
        ),
    ]
