# Generated by Django 5.2.4 on 2025-08-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_alter_student_info_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='parent',
        ),
        migrations.DeleteModel(
            name='parent_info',
        ),
    ]
