# Generated by Django 5.2.5 on 2025-08-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_remove_student_info_parent_delete_parent_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], null=True, verbose_name='Gender'),
        ),
    ]
