# Generated by Django 5.2.5 on 2025-08-13 12:49

import django.db.models.deletion
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0019_alter_project_teacher_message_year_month'),
        ('student', '0027_student_info_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_month', models.DateField(blank=True, default=student.models.get_today_date)),
                ('attended_class', models.BooleanField(verbose_name='class_attended')),
                ('attendence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_class.year_month')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_info')),
            ],
            options={
                'verbose_name': 'attendence',
                'unique_together': {('student', 'attendence')},
            },
        ),
    ]
