# Generated by Django 5.2.5 on 2025-08-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_class', '0020_alter_year_month_unique_together'),
        ('student', '0028_attendence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendence',
            constraint=models.UniqueConstraint(fields=('student', 'date_month'), name='unique_student_date'),
        ),
    ]
