# Generated by Django 5.2.5 on 2025-08-14 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_alter_attendence_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='student.student_info'),
        ),
    ]
